### PR TITLE
PaymentPspReference hardcoded in endpoint URL

### LINKED ISSUE #155: [PW-7090] {paymentPspReference} is being harcoded in the checkout API modifications file
**Describe the bug**
All the methods using `paymentPspReference` are hardcoding `{paymentPspReference}` instead of correctly interpolating the value from the argument. 

**To Reproduce**
1. Check the file https://github.com/Adyen/adyen-go-api-library/blob/main/src/checkout/api_modifications.go#L88

**Expected behavior**
The correct value for the pspReference should be passed to the `a.Client.MakeHTTPPostRequest` call.

**Screenshots**
From the logs: 

image

A correct request using curl:

image

### PR DESCRIPTION
**Pull request by gcatanese**
## Summary
The API modification endpoint is incorrectly built using the `paymentPspReference` string rather than the value of the variable (path parameter).
This PR addresses this problem and creates unit testing (for the failing scenarios) which were missing.

## Tested scenarios
Verify endpoint URL is built correctly and the client request reaches the Adyen backend

**Fixed issue**: 
Fix #155

### CODE REVIEW

**Review by jillingk — APPROVED** [review]

**Review by AlexandrosMor — APPROVED** [review]

File: src/checkout/api_modifications.go [hunk 1]
```diff
@@ -11,96 +11,90 @@
...
- * @param req CreateStandalonePaymentCancelRequest - reference of CreateStandalonePaymentCancelRequest). 
+ * @param req CreateStandalonePaymentCancelRequest - reference of CreateStandalonePaymentCancelRequest).
  * @param ctxs ..._context.Context - optional, for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return StandalonePaymentCancelResource
 */
 func (a Checkout) Cancels(req *CreateStandalonePaymentCancelRequest, ctxs ..._context.Context) (StandalonePaymentCancelResource, *_nethttp.Response, error) {
     res := &StandalonePaymentCancelResource{}
-    httpRes, err := a.Client.MakeHTTPPostRequest(req, res, a.BasePath() + "/cancels", ctxs...)
+    httpRes, err := a.Client.MakeHTTPPostRequest(req, res, a.BasePath()+"/cancels", ctxs...)
```
Comment (AlexandrosMor) [inline src/checkout/api_modifications.go:27]: Could the the BasePath() affect the autogeneration ?

Comment (gcatanese) [reply src/checkout/api_modifications.go:27]: From the specs? It should be fine, but next iteration will use completely different templates (from OpenAPI generator v6.1) so BasePath won't exist or will be built differently.
